import os
import gzip
import time
import pandas as pd
import numpy as np
from Bio import Entrez, SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis

# Required by NCBI Entrez -- replace with your own email before running
Entrez.email = "your_email@example.com"

DATA_DIR = "data"
OUTPUT_DIR = "output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(os.path.join(DATA_DIR, "gene_list.txt")) as f:
    genes = [line.strip() for line in f if line.strip()]

# Yeast codon optimality set (Bennetzen & Hall, 1982 / Sharp & Cowe, 1991)
optimal_codons = ['TTC', 'TTG', 'ATT', 'GTT', 'TCT', 'CCT', 'ACT', 'GCT', 'TAC', 'CAC',
                  'CAG', 'AAC', 'AAG', 'GAC', 'GAG', 'TGC', 'TGG', 'AGA', 'GGT', 'ATG']


def load_dnds(file_path):
    """dN/dS values (YN00 method) from a precomputed, gzipped tab-separated
    file (Gene, YN00_mean columns). Not generated by this pipeline --
    provide your own or an external dN/dS dataset for S. cerevisiae."""
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found -- dN/dS column will be empty.")
        return {}
    try:
        with gzip.open(file_path, 'rt') as f:
            df = pd.read_csv(f, sep='\t')
        dnds_dict = df.set_index('Gene')['YN00_mean'].to_dict()
        for k in dnds_dict:
            if pd.isna(dnds_dict[k]) or dnds_dict[k] == 'NA':
                dnds_dict[k] = np.nan
        print(f"dN/dS loaded successfully ({len(dnds_dict)} genes)")
        return dnds_dict
    except Exception as e:
        print(f"Error loading dN/dS: {e}")
        return {}


dnds_dict = load_dnds(os.path.join(DATA_DIR, "gene_dNdS.tab.gz"))


def fetch_protein_sequence(gene):
    try:
        search_term = f'"{gene}"[Gene] AND Saccharomyces cerevisiae[Organism]'
        handle = Entrez.esearch(db="protein", term=search_term, retmax=1)
        record = Entrez.read(handle)
        handle.close()
        if record['IdList']:
            prot_id = record['IdList'][0]
            handle = Entrez.efetch(db="protein", id=prot_id, rettype="fasta", retmode="text")
            seq = str(SeqIO.read(handle, "fasta").seq)
            handle.close()
            return seq
    except Exception:
        pass
    return None


def fetch_cds_sequence(gene):
    try:
        search_term = f'"{gene}"[Gene] AND Saccharomyces cerevisiae[Organism]'
        handle = Entrez.esearch(db="nucleotide", term=search_term, retmax=1)
        record = Entrez.read(handle)
        handle.close()
        if record['IdList']:
            nucl_id = record['IdList'][0]
            handle = Entrez.efetch(db="nucleotide", id=nucl_id, rettype="fasta_cds_na", retmode="text")
            text = handle.read()
            handle.close()
            cds = ''.join(line.strip() for line in text.splitlines() if not line.startswith('>'))
            return cds.upper()
    except Exception:
        pass
    return None


def fop(cds_seq):
    """Frequency of optimal codons."""
    if not cds_seq or len(cds_seq) % 3 != 0:
        return np.nan
    codons = [cds_seq[i:i + 3] for i in range(0, len(cds_seq), 3)]
    return sum(c in optimal_codons for c in codons) / len(codons)


def codon_diversity(cds_seq):
    if not cds_seq or len(cds_seq) % 3 != 0:
        return np.nan
    codons = [cds_seq[i:i + 3] for i in range(0, len(cds_seq), 3)]
    return len(set(codons)) / len(codons)


data = []
for gene in genes:
    time.sleep(0.34)  # stay under NCBI's rate limit
    prot_seq = fetch_protein_sequence(gene)
    cds_seq = fetch_cds_sequence(gene)
    dnds = dnds_dict.get(gene, np.nan)

    if prot_seq:
        prot = ProteinAnalysis(prot_seq)
        aa = prot.amino_acids_percent
        row = {
            'Gene': gene,
            'dN/dS': dnds,
            'Fop': fop(cds_seq),
            'Gravy': prot.gravy(),
            'Aromaticity': prot.aromaticity(),
            'Net_charge_pH7': prot.charge_at_pH(7.0),
            'Codon_diversity': codon_diversity(cds_seq),
            'Length_aa': len(prot_seq),
            'A_%': aa['A'], 'C_%': aa['C'], 'D_%': aa['D'], 'E_%': aa['E'],
            'F_%': aa['F'], 'G_%': aa['G'], 'H_%': aa['H'], 'I_%': aa['I'],
            'K_%': aa['K'], 'L_%': aa['L'], 'M_%': aa['M'], 'N_%': aa['N'],
            'P_%': aa['P'], 'Q_%': aa['Q'], 'R_%': aa['R'], 'S_%': aa['S'],
            'T_%': aa['T'], 'V_%': aa['V'], 'W_%': aa['W'], 'Y_%': aa['Y'],
        }
        data.append(row)
    else:
        print(f"No protein sequence for {gene}")
        data.append({'Gene': gene, 'dN/dS': dnds})

df = pd.DataFrame(data)
df.to_excel(os.path.join(OUTPUT_DIR, "protein_features_1.xlsx"), index=False)
print("Results saved to output/protein_features_1.xlsx")
